services:
  db:
    image: postgres
    container_name: EXPENSES_TRACKER_DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=expenses-tracker
    ports: 
      - "5432:5432"
    restart: unless-stopped